apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-api
  template:
    metadata:
      labels:
        app: node-api
    spec:
      containers:
      - name: node-api
        image: tu-imagen-de-api
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: mysql-service
        - name: DB_USER
          value: usuario
        - name: DB_PASSWORD
          value: contraseña
        - name: DB_NAME
          value: mi_base_de_datos
---
apiVersion: v1
kind: Service
metadata:
  name: node-api-service
spec:
  selector:
    app: node-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
