version: '3.8'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-mysql
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mi_base_de_datos
      MYSQL_USER: usuario
      MYSQL_PASSWORD: contraseña
    ports:
      - "3306:3306"
    volumes:
      - ./BD:/docker-entrypoint-initdb.d

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-api
    environment:
      DB_HOST: db
      DB_USER: usuario
      DB_PASSWORD: contraseña
      DB_NAME: mi_base_de_datos
    ports:
      - "3000:3000"
    depends_on:
      - db
