version: "3.9"
services:
  database:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: CrudNodejs
    ports:
      - "3306:3306"
    volumes:
      - ./BD:/docker-entrypoint-initdb.d # Carga el archivo estudiantes.sql

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crud-api
    ports:
      - "3000:3000" # Puerto de la API en 3000
    environment:
      DB_HOST: database
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: CrudNodejs
    depends_on:
      - database
