# Imagen base de MySQL
FROM mysql:8.0

# Copiar el archivo SQL al contenedor
COPY BD/estudiantes.sql /docker-entrypoint-initdb.d/

# Establecer variables de entorno para la base de datos
ENV MYSQL_ROOT_PASSWORD=root_password
ENV MYSQL_DATABASE=mi_base_de_datos
ENV MYSQL_USER=usuario
ENV MYSQL_PASSWORD=contraseña
